name: Systematic Vision
favicon: null
layout_spectrum: 0.87992
typography_spectrum: 0.73463
title: 'Systematic Vision Imaging Components, Services and Solutions'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#97a4ac'
    - '#336ab4'
    - '#c7cfd3'
    - '#61676c'
  brandStrength: 0.8854471733793616
  lightness: 0.629833297803998
  saturation: 0.9802116572391242
  rhythmicContrast: 0.5410764485131949
purpose: []
